### ISSUE TITLE
Connect button + states

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/nextjs-penumbra-client-example#2]
At the moment, the current design of this example has some of the default Vercel content. We should scrap this and show a UI that focuses on extension connect state + user data.

### Extension state

A button with three states:
- Install Prax (links to chrome web store)
- Connect Prax (initiates connection)
- Connected

### User data

- Address: `<PraxAddress />` currently uses `@connectrpc/connect-query` to query for address. We should have an input box that allows users to type in an address to show how useQuery automatically re-renders.
- Balances: We should have a button that requests balances and displays denoms + amounts. It specifically should not use useQuery to show how our transport can be used by constructing a client manually. 

No priority on design or css. Can be without it.

**Comment by VanishMax** [comment]
implemented in #4
